<?php 
    // Config plugins
    $labels = array(
        'name' => _x('Todos los productos', 'Post type general name', 'textdomain'),
        'singular_name' => _x('Productos Lif', 'Post type singular name', 'textdomain'),
        'menu_name' => _x('Productos Lif', 'Admin Menu text', 'textdomain'),
        'name_admin_bar' => _x('Productos Lif', 'Add New on Toolbar', 'textdomain'),
        'add_new' => __('Add New', 'textdomain'),
        'add_new_item' => __('Add New Exposición', 'textdomain'),
        'new_item' => __('New Exposición', 'textdomain'),
        'edit_item' => __('Edit Contents', 'textdomain'),
        'view_item' => __('View productos', 'textdomain'),
        'all_items' => __('All productos', 'textdomain'),
        'search_items' => __('Search producto', 'textdomain'),
        'parent_item_colon' => __('Parent Productos Lif:', 'textdomain'),
        'not_found' => __('Sin contenido...', 'textdomain'),
        'not_found_in_trash' => __('No productos found in Trash.', 'textdomain'),
        'featured_image' => _x('Productos Lif Cover Image', 'Overrides the “Featured Image” phrase for this post type. Added in 4.3', 'textdomain'),
        'set_featured_image' => _x('Set productos', 'Overrides the “Set featured image” phrase for this post type. Added in 4.3', 'textdomain'),
        'remove_featured_image' => _x('Remove cover image', 'Overrides the “Remove featured image” phrase for this post type. Added in 4.3', 'textdomain'),
        'use_featured_image' => _x('Use as cover image', 'Overrides the “Use as featured image” phrase for this post type. Added in 4.3', 'textdomain'),
        'archives' => _x('Productos Lif archives', 'The post type archive label used in nav menus. Default “Post Archives”. Added in 4.4', 'textdomain'),
        'insert_into_item' => _x('Insert into productos', 'Overrides the “Insert into post”/”Insert into page” phrase (used when inserting media into a post). Added in 4.4', 'textdomain'),
        'uploaded_to_this_item' => _x('Uploaded to this productos', 'Overrides the “Uploaded to this post”/”Uploaded to this page” phrase (used when viewing media attached to a post). Added in 4.4', 'textdomain'),
        'filter_items_list' => _x('Filter productos list', 'Screen reader text for the filter links heading on the post type listing screen. Default “Filter posts list”/”Filter pages list”. Added in 4.4', 'textdomain'),
        'items_list_navigation' => _x('Productos Lif list navigation', 'Screen reader text for the pagination heading on the post type listing screen. Default “Posts list navigation”/”Pages list navigation”. Added in 4.4', 'textdomain'),
        'items_list' => _x('Productos Lif list', 'Screen reader text for the items list heading on the post type listing screen. Default “Posts list”/”Pages list”. Added in 4.4', 'textdomain'),
    );